# Generated by Django 5.2.15 on 2026-07-04 09:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_balance', models.PositiveIntegerField(default=0)),
                ('total_tokens_earned', models.PositiveBigIntegerField(default=0)),
                ('total_tokens_spent', models.PositiveBigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Wallet',
                'verbose_name_plural': 'User Wallets',
                'db_table': 'user_wallets',
            },
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('reason', models.CharField(choices=[('INITIAL_ALLOCATION', 'Initial Allocation'), ('QUIZ_GENERATION', 'Quiz Generation'), ('QUIZ_EVALUATION', 'Quiz Evaluation'), ('OCR_PROCESSING', 'OCR Processing'), ('FILE_PROCESSING', 'File Processing'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('REFUND', 'Refund')], max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('balance_after_transaction', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.userwallet')),
            ],
            options={
                'verbose_name': 'Token Transaction',
                'verbose_name_plural': 'Token Transactions',
                'db_table': 'token_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
