# Generated by Django 5.2.15 on 2026-07-04 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['wallet'], name='token_trans_wallet__f81bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['created_at'], name='token_trans_created_4c5cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='userwallet',
            index=models.Index(fields=['user'], name='user_wallet_user_id_b06072_idx'),
        ),
    ]
