# Generated by Django 5.2.15 on 2026-07-05 18:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('EMPTY', 'Empty'), ('READY_FOR_PROCESSING', 'Ready for Processing'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='EMPTY', max_length=30)),
                ('processing_signature', models.CharField(blank=True, max_length=64, null=True)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
