# Generated by Django 5.2.15 on 2026-07-07 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0002_workspace_unique_workspace_title_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('VERIFYING', 'Verifying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CLEANUP_PENDING', 'Cleanup Pending'), ('CLEANED', 'Cleaned')], default='PENDING', max_length=32)),
                ('expected_file_count', models.PositiveIntegerField()),
                ('uploaded_file_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cleanup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_total_size', models.BigIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='workspace.workspace')),
            ],
            options={
                'db_table': 'upload_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadSessionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=1024, unique=True)),
                ('role', models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('NOTES', 'Notes')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=32)),
                ('expected_file_size', models.BigIntegerField()),
                ('expected_content_type', models.CharField(max_length=100)),
                ('uploaded_file_size', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('object_last_modified', models.DateTimeField(blank=True, null=True)),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files.uploadsession')),
            ],
            options={
                'db_table': 'upload_session_files',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['workspace'], name='upload_sess_workspa_f803d5_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['user'], name='upload_sess_user_id_680687_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['status'], name='upload_sess_status_f1db9b_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsessionfile',
            index=models.Index(fields=['upload_session'], name='upload_sess_upload__7d8cf5_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsessionfile',
            index=models.Index(fields=['status'], name='upload_sess_status_af41d6_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsessionfile',
            index=models.Index(fields=['role'], name='upload_sess_role_2ba305_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsessionfile',
            index=models.Index(fields=['storage_key'], name='upload_sess_storage_dfb60a_idx'),
        ),
    ]
