# Generated by Django 5.2.15 on 2026-07-07 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('workspace', '0002_workspace_unique_workspace_title_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=1024, unique=True)),
                ('role', models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('NOTES', 'Notes')], max_length=32)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('etag', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROCESSING', 'Processing'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=32)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('upload_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_files', to='files.uploadsession')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workspace.workspace')),
            ],
            options={
                'db_table': 'files',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['workspace'], name='files_workspa_ed3822_idx'), models.Index(fields=['role'], name='files_role_38c7d4_idx'), models.Index(fields=['status'], name='files_status_179a06_idx'), models.Index(fields=['file_hash'], name='files_file_ha_3fed72_idx'), models.Index(fields=['uploaded_by'], name='files_uploade_eeab7f_idx')],
            },
        ),
    ]
