# Generated by Django 5.2.15 on 2026-07-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='etag',
        ),
    ]
