# Generated by Django 5.2.15 on 2026-07-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_file_etag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFYING', 'Verifying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CLEANED', 'Cleaned')], default='PENDING', max_length=32),
        ),
        migrations.AlterField(
            model_name='uploadsessionfile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=32),
        ),
    ]
