# Generated by Django 5.2.15 on 2026-07-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_uploadsession_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='uploadsessionfile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('REGISTERED', 'Registered')], default='PENDING', max_length=32),
        ),
    ]
